name: Build Docs

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade --user pip setuptools
          python3 -m pip install --upgrade --user sphinx recommonmark sphinx_rtd_theme rstcheck

      - run: |
          export PATH=$PATH:/home/runner/.local/bin
          rstcheck -r ./

      - name: Build docs
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          errlog=$(mktemp)
          make html 2> $errlog
          if [[ -s "$errlog" ]]; then
            cat $errlog
            exit 1
          else
              echo "OK"
          fi

      - uses: actions/upload-artifact@v2
        with:
          name: asset-tracker-docs-${{ github.sha }}
          path: build/html/
