name: PR checks

on: pull_request

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Test
        run: npm test

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade --user pip setuptools
          python3 -m pip install --upgrade --user sphinx recommonmark sphinx_rtd_theme rstcheck

      - run: |
          export PATH=$PATH:/home/runner/.local/bin
          rstcheck -r ./

      - name: Build docs
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          errlog=$(mktemp)
          make html 2> $errlog
          if [[ -s "$errlog" ]]; then
            cat $errlog
            exit 1
          else
              echo "OK"
          fi

      - uses: actions/upload-artifact@v2
        with:
          name: asset-tracker-docs-${{ github.sha }}
          path: build/html/
