name: Test and Release

on: publish-docs

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade --user pip setuptools
          python3 -m pip install --upgrade --user sphinx recommonmark sphinx_rtd_theme rstcheck

      - name: Generate Documentation
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          export VERSION=`git tag --contains ${{ github.event.client_payload.sha }} | tr -d '\n'`
          make html

      - name: Publish Documentation
        run: |
          echo "machine github.com login accesskey password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd build/html
          touch .nojekyll
          git init
          git add -A
          git commit -m "Update documentation to version ${GITHUB_REF}"
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
